const $ = id => document.getElementById(id);
const canvas = $("scene");
const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera(38, 1, 0.1, 200);
camera.position.set(28, 20, 30);
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
const lowPowerDevice = window.matchMedia("(pointer: coarse)").matches;
renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, lowPowerDevice ? 1.25 : 2));
renderer.shadowMap.enabled = !lowPowerDevice;
const controls = new THREE.OrbitControls(camera, canvas);
controls.enableDamping = true;
controls.target.set(0, 12, 0);
scene.add(new THREE.HemisphereLight(0xdbe9ed, 0x27343a, 1.7));
const sun = new THREE.DirectionalLight(0xffe2b0, 2.2);
sun.position.set(18, 35, 12); sun.castShadow = !lowPowerDevice; scene.add(sun);
const ground = new THREE.Mesh(new THREE.PlaneGeometry(160, 160), new THREE.MeshStandardMaterial({ color: 0xb9c9c8, roughness: 0.9 }));
ground.rotation.x = -Math.PI / 2; ground.receiveShadow = true; scene.add(ground);
const grid = new THREE.GridHelper(160, 40, 0x6d8383, 0x9aabaa); grid.position.y = 0.02; scene.add(grid);
let structural; let building; let motion; let activeFrequency = 1; let running = false; let elapsed = 0; let shakePhase = 0; let last = performance.now(); let waveHistory = [];
const visualMotionScale = 5;
const viewportPanel = $("viewport-panel");
const timeOfDay = $("time-of-day");
function updateTimeOfDay(isDay) { const night = !isDay; timeOfDay.parentElement.classList.toggle("night", night); sun.intensity = night ? 0.35 : 2.2; sun.color.set(night ? 0x8faed1 : 0xffe2b0); scene.getObjectByProperty("type", "HemisphereLight").intensity = night ? 0.65 : 1.7; viewportPanel.style.background = night ? "linear-gradient(180deg, #101820 0%, #1a2932 63%, #26343a 63%, #1d292d 100%)" : "linear-gradient(180deg, #101820 0%, #172932 63%, #26343a 63%, #1d292d 100%)"; }
timeOfDay.addEventListener("change", () => updateTimeOfDay(timeOfDay.checked));
updateTimeOfDay(timeOfDay.checked);
function values() { return { stories: +$("stories").value, width: +$("width").value, pgaG: +$("pga").value, freqHz: +$("frequency").value, durationS: +$("duration").value, material: "concrete", foundation: "strong", dampingRatio: 0.025, stiffnessMult: 1, floorHeight: 3.2, waveform: $("waveform").value }; }
function rebuild() { if (building) building.dispose(); structural = new ShearBuilding(values()); building = new BuildingView(scene, structural); const height = structural.stories * structural.floorHeight; const distance = Math.max(42, height * 1.6); controls.target.set(0, height / 2, 0); camera.position.set(distance * 0.72, height * 0.58, distance); controls.update(); $("natural-frequency").textContent = structural.naturalFreqHz.toFixed(2) + " Hz"; }
function resize() { const box = canvas.parentElement.getBoundingClientRect(); renderer.setSize(box.width, box.height, false); camera.aspect = box.width / Math.max(box.height, 1); camera.updateProjectionMatrix(); }
let lastReportKey = "";
function updateDamageReport() { const elevation = $("elevation"); const rows = $("damage-rows"); const reportKey = structural.stories + ":" + structural.damageState.join(","); if (reportKey === lastReportKey) return; lastReportKey = reportKey; elevation.style.setProperty("--floor-count", structural.stories); if (elevation.children.length !== structural.stories) { elevation.innerHTML = ""; rows.innerHTML = ""; for (let i = structural.stories - 1; i >= 0; i--) { const block = document.createElement("span"); block.dataset.floor = i; elevation.appendChild(block); const row = document.createElement("tr"); row.innerHTML = `<td>${i + 1}</td><td data-drift></td><td data-danger></td>`; rows.appendChild(row); } } const blocks = [...elevation.children]; const tableRows = [...rows.children]; for (let i = 0; i < structural.stories; i++) { const state = structural.damageState[i]; const danger = { safe: "low", warning: "moderate", severe: "high", "collapsed-story": "critical" }[state] || "low"; const block = blocks[structural.stories - 1 - i]; block.className = state; const row = tableRows[structural.stories - 1 - i]; row.className = state; row.querySelector("[data-drift]").textContent = (structural.peakDrift[i] * 100).toFixed(2) + "%"; row.querySelector("[data-danger]").textContent = danger; } }
function updateReadout() { const peak = structural.maxPeakDrift(); const state = structural.overallDamageClass(); const floorState = peak.floor < 0 ? "safe" : structural.damageState[peak.floor]; const danger = { safe: "Low", warning: "Moderate", severe: "High", "collapsed-story": "Critical" }[floorState] || "Low"; $("elapsed").textContent = elapsed.toFixed(1) + " s"; $("roof-displacement").textContent = structural.maxRoofDisplacement().toFixed(2) + " m"; $("peak-drift").textContent = (peak.ratio * 100).toFixed(2) + "%"; const verdict = $("verdict"); verdict.textContent = state.toUpperCase(); verdict.className = "verdict " + state; $("damage-story").textContent = peak.floor < 0 ? "Floor: None affected" : "Floor: " + (peak.floor + 1) + " most affected"; $("damage-level").textContent = "Danger level: " + danger; updateDamageReport(); }
function clearScreenShake() { canvas.style.transform = "translate3d(0, 0, 0)"; }
const wave = $("wave-canvas"); const waveContext = wave.getContext("2d"); let waveWidth = 0; let waveHeight = 0; let waveRatio = 0;
function drawWave(accel = 0) { const width = Math.max(1, wave.clientWidth); const height = Math.max(1, wave.clientHeight); const ratio = Math.min(window.devicePixelRatio || 1, 2); if (width !== waveWidth || height !== waveHeight || ratio !== waveRatio) { waveWidth = width; waveHeight = height; waveRatio = ratio; wave.width = width * ratio; wave.height = height * ratio; waveContext.setTransform(ratio, 0, 0, ratio, 0, 0); } waveContext.clearRect(0, 0, width, height); waveHistory.push(accel / 9.80665); if (waveHistory.length > 180) waveHistory.shift(); waveContext.strokeStyle = "rgba(142, 160, 160, .45)"; waveContext.lineWidth = 1; waveContext.beginPath(); waveContext.moveTo(0, height / 2); waveContext.lineTo(width, height / 2); waveContext.stroke(); waveContext.strokeStyle = "#f0c44c"; waveContext.lineWidth = 2; waveContext.beginPath(); waveHistory.forEach((value, index) => { const x = index / 179 * width; const y = height / 2 - Math.max(-1, Math.min(1, value)) * height * 0.42; index ? waveContext.lineTo(x, y) : waveContext.moveTo(x, y); }); waveContext.stroke(); $("wave-readout").textContent = (accel / 9.80665).toFixed(2) + " g"; }
function start() { const settings = values(); rebuild(); motion = new GroundMotion(settings, 1 / 120); activeFrequency = settings.freqHz; elapsed = 0; shakePhase = 0; running = true; $("start-btn").textContent = "Shake in progress"; $("status").textContent = "Ground motion active"; }
function reset() { running = false; elapsed = 0; waveHistory = []; clearScreenShake(); drawWave(); rebuild(); $("start-btn").textContent = "Start shake"; $("status").textContent = "Ready to simulate"; updateReadout(); }
function applySettings() { running = false; elapsed = 0; waveHistory = []; clearScreenShake(); drawWave(); rebuild(); $("start-btn").textContent = "Start shake"; $("status").textContent = "Settings updated"; updateReadout(); }
const menu = $("controls-menu");
function setMenuOpen(open) { if (!open && menu.contains(document.activeElement)) $("menu-toggle").focus(); menu.classList.toggle("open", open); menu.setAttribute("aria-hidden", String(!open)); $("menu-toggle").setAttribute("aria-expanded", String(open)); }
$("menu-toggle").addEventListener("click", () => setMenuOpen(!menu.classList.contains("open")));
$("close-menu").addEventListener("click", () => setMenuOpen(false));
document.addEventListener("click", event => { if (menu.classList.contains("open") && !menu.contains(event.target) && event.target !== $("menu-toggle")) setMenuOpen(false); });
document.addEventListener("keydown", event => { if (event.key === "Escape") setMenuOpen(false); });
const report = $("damage-report"); const reportTitle = $("report-title"); let drag = null;
const reportToggle = document.createElement("button"); reportToggle.className = "report-toggle"; reportToggle.textContent = "-"; reportToggle.title = "Shrink result"; reportToggle.setAttribute("aria-label", "Shrink result"); reportTitle.appendChild(reportToggle);
reportToggle.addEventListener("pointerdown", event => event.stopPropagation()); reportToggle.addEventListener("click", event => { event.stopPropagation(); const compact = report.classList.toggle("compact"); reportToggle.textContent = compact ? "+" : "-"; reportToggle.title = compact ? "Expand result" : "Shrink result"; reportToggle.setAttribute("aria-label", compact ? "Expand result" : "Shrink result"); });
report.addEventListener("pointerdown", event => { const rect = report.getBoundingClientRect(); drag = { x: event.clientX - rect.left, y: event.clientY - rect.top }; report.style.transform = "none"; report.setPointerCapture(event.pointerId); });
report.addEventListener("pointermove", event => { if (!drag) return; const panel = $("viewport-panel").getBoundingClientRect(); report.style.left = Math.max(8, Math.min(panel.width - report.offsetWidth - 8, event.clientX - panel.left - drag.x)) + "px"; report.style.top = Math.max(8, Math.min(panel.height - report.offsetHeight - 8, event.clientY - panel.top - drag.y)) + "px"; });
report.addEventListener("pointerup", () => { drag = null; });
const metrics = $("metrics-dock"); let metricsDrag = null;
metrics.addEventListener("pointerdown", event => { const rect = metrics.getBoundingClientRect(); metricsDrag = { x: event.clientX - rect.left, y: event.clientY - rect.top }; metrics.style.transform = "none"; metrics.style.left = rect.left - $("viewport-panel").getBoundingClientRect().left + "px"; metrics.style.top = rect.top - $("viewport-panel").getBoundingClientRect().top + "px"; metrics.setPointerCapture(event.pointerId); });
metrics.addEventListener("pointermove", event => { if (!metricsDrag) return; const panel = $("viewport-panel").getBoundingClientRect(); metrics.style.left = Math.max(8, Math.min(panel.width - metrics.offsetWidth - 8, event.clientX - panel.left - metricsDrag.x)) + "px"; metrics.style.top = Math.max(8, Math.min(panel.height - metrics.offsetHeight - 8, event.clientY - panel.top - metricsDrag.y)) + "px"; });
metrics.addEventListener("pointerup", () => { metricsDrag = null; });
const waveDock = $("wave-dock"); const waveTitle = $("wave-title"); let waveDrag = null;
waveDock.addEventListener("pointerdown", event => { const rect = waveDock.getBoundingClientRect(); waveDrag = { x: event.clientX - rect.left, y: event.clientY - rect.top }; waveDock.style.transform = "none"; waveDock.style.left = rect.left - $("viewport-panel").getBoundingClientRect().left + "px"; waveDock.style.top = rect.top - $("viewport-panel").getBoundingClientRect().top + "px"; waveDock.setPointerCapture(event.pointerId); });
	waveDock.addEventListener("pointermove", event => { if (!waveDrag) return; const panel = $("viewport-panel").getBoundingClientRect(); waveDock.style.left = Math.max(8, Math.min(panel.width - waveDock.offsetWidth - 8, event.clientX - panel.left - waveDrag.x)) + "px"; waveDock.style.top = Math.max(8, Math.min(panel.height - waveDock.offsetHeight - 8, event.clientY - panel.top - waveDrag.y)) + "px"; });
	waveDock.addEventListener("pointerup", () => { waveDrag = null; });
$("start-btn").addEventListener("click", start); $("reset-btn").addEventListener("click", reset);
["stories", "width", "pga", "frequency", "duration"].forEach(id => $(id).addEventListener("input", () => { const v = $(id).value; $(id + "-value").textContent = id === "width" ? v + " m" : id === "pga" ? (+v).toFixed(2) + " g" : id === "frequency" ? (+v).toFixed(2) + " Hz" : id === "duration" ? v + " s" : v; applySettings(); }));
["waveform"].forEach(id => $(id).addEventListener("change", applySettings));
$("reset-camera-btn").addEventListener("click", () => { camera.position.set(28, 20, 30); controls.target.set(0, 12, 0); controls.update(); });
$("viewport-toggle").addEventListener("click", () => { const expanded = $("viewport-panel").classList.toggle("expanded"); $("viewport-toggle").setAttribute("aria-pressed", expanded); $("viewport-toggle").title = expanded ? "Collapse viewport" : "Expand viewport"; requestAnimationFrame(resize); });
const uiToggle = document.createElement("button"); uiToggle.className = "cam-btn ui-toggle"; uiToggle.id = "ui-toggle"; uiToggle.textContent = "◉"; uiToggle.title = "Hide interface"; uiToggle.setAttribute("aria-label", "Hide interface"); uiToggle.setAttribute("aria-pressed", "false"); $("viewport-panel").querySelector(".camera-dock").appendChild(uiToggle);
uiToggle.addEventListener("click", () => { const hidden = $("viewport-panel").classList.toggle("ui-hidden"); uiToggle.setAttribute("aria-pressed", hidden); uiToggle.textContent = hidden ? "◎" : "◉"; uiToggle.title = hidden ? "Show interface" : "Hide interface"; uiToggle.setAttribute("aria-label", hidden ? "Show interface" : "Hide interface"); });
function frame(now) { const dt = Math.min((now - last) / 1000, 1 / 30); last = now; if (running && motion) { const index = Math.floor(elapsed * 120); const sample = motion.sampleIndex(index); structural.step(dt, sample.accel); elapsed += dt; shakePhase += dt * Math.PI * 2 * activeFrequency; if (structural.collapsed) { building.collapse(structural.collapseInitiatingStory); if (building.animateCollapse(dt)) running = false; } else { building.updatePose(sample.disp * visualMotionScale); } const intensity = Math.min(1, Math.abs(sample.accel) / 9.80665); const shakePixels = 1.5 + intensity * 10; canvas.style.transform = `translate3d(${Math.sin(shakePhase) * shakePixels}px, ${Math.cos(shakePhase * 1.17) * shakePixels * 0.65}px, 0)`; drawWave(sample.accel); updateReadout(); if (index >= motion.totalSteps() - 1 || (structural.collapsed && !running)) { clearScreenShake(); $("start-btn").textContent = "Start shake"; $("status").textContent = structural.collapsed ? "Collapse detected" : "Shake complete"; } } else { clearScreenShake(); } controls.update(); renderer.render(scene, camera); requestAnimationFrame(frame); }
const viewportObserver = new ResizeObserver(() => { resize(); drawWave(); });
viewportObserver.observe($("viewport-panel"));
window.addEventListener("resize", () => { resize(); drawWave(); }); rebuild(); resize(); drawWave(); updateReadout(); requestAnimationFrame(frame);
